# version: '3'
# services:
#   frontend:
#     build: 
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db

version: '3'
services:
  frontend:
    build:
      context: ./frontend-final
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coderush
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
